// Try - Catch
console.log(1+1);

try {
	authUser();
} catch (error) {
	console.log(error);
}

console.log(2+2);